### ISSUE TITLE
How to setup multi-site production

### ISSUE THREAD

**Issue by victor-abz** [Henry-Do-Su/frappe_deployer#1]
How to setup multi-site support in production

**Comment by Henry-Do-Su** [comment]
Hi,
For multitenancy I recommend you follow the Frappe official repo, and copy in the required code, to my docker compose file.
For example: https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md
Im currently busy with many other projects and unless I get requests from a couple people for this or more features I cant find the time at the moment.
